### ISSUE TITLE
Installation fails "uninitialized constant ChiliProject (NameError)"

### ISSUE THREAD

**Issue by christian-brose** [martin-denizet/wiking#6]
Hi,
i'm currently migrating my redmine from 3 to 4 and therefore all the plugins. Wiking is the last one and the only I can't get to work on 4.2.1.

After installation I get the following error.
````
/usr/src/redmine/plugins/wiking/lib/chiliproject/liquid/tags/wiking_liquid_hook.rb:1:in `<top (required)>': uninitialized constant ChiliProject (NameError)
````
I hope you can help.
Thx,
Christian

```
Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.7.3-p183 (2021-04-05) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
```

**Comment by martin-denizet** [comment]
Hello! Thanks for the report.
I could not reproduce the issue on version 1.1.3 so far. Which version of wiking are you using please?

**Comment by christian-brose** [comment]
Thanks for helping.

I'm using the master branch of this git repository. So version 1.1.3.

For me it is a reproduceable error.

1. git clone
2. bundle exec rake redmine:plugins:migrate RAILS_ENV=production
3. restart

relevant log entries after restart:

```
/usr/src/redmine/plugins/wiking/lib/chiliproject/liquid/tags/wiking_liquid_hook.rb:1:in `<top (required)>': uninitialized constant ChiliProject (NameError),
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require',
	from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies/interlock.rb:14:in `block in loading',
	from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/concurrency/share_lock.rb:151:in `exclusive',
	from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies/interlock.rb:13:in `loading',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:477:in `each',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:477:in `block in eager_load!',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:475:in `each',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:475:in `eager_load!',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:356:in `eager_load!',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application/finisher.rb:69:in `each',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each',
	from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!',
	from /usr/src/redmine/config/environment.rb:16:in `<top (required)>',
	from config.ru:3:in `block in <main>',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:27:in `app',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling',
	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:53:in `start',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:147:in `block in perform',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `tap',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `perform',
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run',
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command',
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke',
	from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>',
	from bin/rails:4:in `require',
	from bin/rails:4:in `<main>'
```

Any Idea?
Thanks!

Perhaps it helps: I'm using docker

**Comment by martin-denizet** [comment]
I could try a blind fix but to really understand the issue could you please send the list of plugins installed and the server you are using? (Puma?)
